import { Grammar } from '../types';

export const arubaApGrammar: Grammar = {
  name: 'aruba-ap',
  commands: [
    'show', 'config', 'interface', 'ssid', 'wlan', 'ap',
    'dot11g', 'dot11a', 'radio', 'arm', 'ids', 'wids',
    'firewall', 'netservice', 'acl', 'user-role', 'vlan',
    'ip', 'ntp', 'snmp', 'syslog', 'aaa', 'radius', 'tacacs',
    'crypto', 'certificate', 'ikev2', 'ipsec', 'gre', 'tunnel',
    'provision-ap', 'reprovision', 'reset', 'halt', 'boot',
    'upgrade', 'backup', 'restore', 'ping', 'traceroute',
    'ap-debug', 'remote-debug', 'coredump', 'iap-master',
    'iap-vc', 'cluster', 'virtual-controller', 'enet',
    'mesh', 'uplink', 'provision', 'instant', 'swarm',
    'spectrum', 'wms', 'ids', 'wids', 'arm-rf-domain',
  ],
  subcommands: [
    'ssid-profile', 'ap-group', 'virtual-ap', 'ht-ssid-profile',
    'radio-profile', 'arm-profile', 'ids-profile', 'wmm',
    'channel', 'power', 'beacon', 'probe-response', 'rts',
    'fragmentation', 'rts-threshold', 'mode', 'band',
    'encryption', 'wpa', 'wpa2', 'wpa3', 'tkip', 'aes',
    'psk', '802.1x', 'captive-portal', 'mac-auth', 'dot1x',
    'role', 'access-list', 'service', 'destination', 'source',
    'port', 'protocol', 'permit', 'deny', 'any', 'log',
    'nat', 'dhcp', 'dns', 'gateway', 'vlan-id', 'forward-mode',
    'tunnel', 'decrypt-tunnel', 'bridge', 'split-tunnel',
    'broadcast-filter', 'multicast', 'dynamic-multicast',
    'ampdu', 'amsdu', 'short-gi', 'ldpc', 'tx-power',
    'max-clients', 'basic-rates', 'supported-rates', 'mbssid',
    'dot11g-radio-profile', 'dot11a-radio-profile',
    'a-channel', 'g-channel', 'min-tx-power', 'max-tx-power',
    'band-steering-mode', 'client-aware', 'air-time-fairness',
    'client-match', 'wmm-background', 'wmm-best-effort',
    'wmm-voice', 'wmm-video', 'opmode',
    'legacy', 'a-n', 'a-ac', 'g-n', 'g-ac', 'ax',
    'master-ip', 'master-redundancy', 'eth', 'wifi', 'radio', 'mgmt',
  ],
  keywords: [
    'enable', 'disable', 'default', 'exit', 'end', 'quit',
    'all', 'none', 'any', 'every', 'not', 'and', 'or',
    'required', 'optional', 'mandatory', 'preferred',
    'indoor', 'outdoor', 'campus', 'instant', 'remote',
    'opensystem', 'shared-key', 'dynamic-wep', 'static-wep',
    'a', 'g', 'ng', 'na', 'ac', 'ax', 'bg',
    'high-throughput', 'very-high-throughput', 'he',
    'tx-chains', 'rx-chains', 'vht', 'he', 'mcs',
    'sgi', 'ldpc', 'stbc', 'txbf',
  ],
  operators: ['|', '>', '<'],
  flags: ['--help', '-h'],
  values: {
    ipAddress: /\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/,
    macAddress: /\b(?:[0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}\b/,
    vlanId: /\bvlan\s*(?:[1-9][0-9]{0,3}|409[0-5]|40[0-8][0-9]|[1-3][0-9]{3}|[1-9][0-9]{0,2})\b/,
    interfaceName: /\b(?:eth\d+|wifi\d+|radio\d+|mgmt)\b/,
    number: /\b\d+\b/,
  },
  promptPattern: /^\(?(?:[A-Za-z0-9][A-Za-z0-9-_]*(?:-VC)?\s*[\(#>]\s?)/,
};
