import { Grammar } from '../types';

export const arubaCxGrammar: Grammar = {
  name: 'aruba-cx',
  commands: [
    'show', 'display', 'config', 'configure', 'interface', 'vlan', 'router', 'ip', 'aaa',
    'ntp', 'snmp', 'logging', 'spanning-tree', 'lacp', 'vrf',
    'route-map', 'prefix-list', 'access-list', 'dhcp', 'dns',
    'hostname', 'username', 'password', 'enable', 'disable',
    'exit', 'end', 'copy', 'write', 'erase', 'ping', 'traceroute',
    'ssh', 'telnet', 'crypto', 'certificate', 'tacacs', 'radius',
    'lldp', 'cdp', 'mac-address-table', 'arp', 'clock',
    'banner', 'line', 'console', 'vty', 'mgmt', 'led', 'reboot',
    'checkpoint', 'rollback', 'upload', 'download', 'system',
    'port-group', 'lag', 'mirror', 'sflow', 'qos', 'acl',
    'evpn', 'vxlan', 'bgp', 'ospf', 'isis', 'pim', 'igmp',
    'link-keepalive', 'fault-monitor', 'track', 'ip-sla',
    'usb', 'tftp', 'scp', 'sftp', 'ztp', 'transceiver',
    'vsx-sync', 'vsx-update', 'apply', 'checkpoint-post',
    'delete', 'alias', 'include', 'openflow', 'port-access',
    'device-profile', 'role', 'url', 'uba', 'uba-device',
    'loop-protect', 'storm-control', 'udld', 'vlt', 'scheduled',
    'job', 'timesync', 'ntp', 'clock', 'timezone',
  ],
  subcommands: [
    'access', 'trunk', 'hybrid', 'allowed', 'native', 'untagged',
    'tagged', 'shutdown', 'no shutdown', 'description', 'mtu',
    'speed', 'duplex', 'flow-control', 'auto-negotiate',
    'routing', 'vrrp', 'vip', 'address', 'gateway', 'dns-server',
    'domain', 'tftp-server', 'syslog', 'host', 'community',
    'version', 'trap', 'passive', 'active', 'mode', 'timers',
    'area', 'network', 'neighbor', 'redistribute', 'aggregate',
    'summary', 'default-information', 'prefix', 'rule', 'action',
    'permit', 'deny', 'log', 'count', 'remark', 'sequence',
    'pool', 'range', 'exclude', 'option', 'relay', 'snooping',
    'authentication', 'authorization', 'accounting', 'group',
    'server', 'priority', 'source-interface', 'vrf', 'bgp-as',
    'local-preference', 'med', 'next-hop', 'update-source',
    'secret', 'privilege', 'access-level', 'member',
    'hash', 'min-score', 'include-criteria', 'vsx-sync',
    'vsx-update', 'peer', 'isl', 'keepalive', 'linkup-delay',
    'evi', 'rd', 'route-target', 'encapsulation', 'vni',
    'underlying', 'import', 'export', 'afi', 'safi',
    'name', 'apply', 'qos-trust', 'trust', 'dscp-map',
    'queue-profile', 'schedule-profile', 'reassembly',
    'jumbo', 'default-vlan', 'voice', 'poe', 'poe-priority',
    'unknown-vlans', 'discard', 'ratelimit', 'client-limit',
    'mvrp', 'gvrp', 'bpdu', 'stp', 'rstp', 'mstp',
    'edge-port', 'link-type', 'max-hops', 'forward-delay',
    'hello-time', 'max-age', 'bridge-priority',
  ],
  keywords: [
    'enable', 'disable', 'default', 'exit', 'end', 'quit',
    'yes', 'no', 'all', 'none', 'any', 'every', 'not',
    'and', 'or', 'in', 'out', 'both', 'full', 'half',
    'auto', 'force', 'strict', 'loose', 'inside', 'outside',
    'local', 'global', 'unicast', 'multicast', 'broadcast',
    'static', 'dynamic', 'connected', 'persistent', 'volatile',
    'primary', 'secondary', 'persistent', 'preferred',
    'preempt', 'delay', 'auth-md5', 'auth-sha',
    'point-to-point', 'point-to-multipoint', 'nbma',
    'dr', 'bdr', 'neighbor', 'area', 'stub', 'nssa',
    'totally-stubby', 'default-originate', 'always',
    'metric', 'metric-type', 'tag', 'route-map',
  ],
  operators: ['|', '>', '<', '&&', '||', '!', ';', '&', '>>', '2>', '2>&1'],
  flags: ['--help', '-h', '--verbose', '-v', '--detail', '--json'],
  values: {
    ipAddress: /\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(?:\/(?:[0-9]|[1-2][0-9]|3[0-2]))?\b/,
    macAddress: /\b(?:[0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}\b/,
    vlanId: /\bvlan\s+(?:[1-9][0-9]{0,3}|409[0-5]|40[0-8][0-9]|[1-3][0-9]{3}|[1-9][0-9]{0,2})\b/,
    interfaceName: /\b(?:\d+\/\d+\/\d+(?:-\d+\/\d+\/\d+)?|lag\d+|loopback\d+|vlan\d+)\b/,
    number: /\b\d+\b/,
  },
  promptPattern: /^\(?(?:[A-Za-z0-9][A-Za-z0-9-_]*\(?(?:config[^)]*\))?\s*[#>]\s?)/,
};
