import { Grammar } from '../types';

export const arubaCtrlGrammar: Grammar = {
  name: 'aruba-controller',
  commands: [
    'show', 'configure', 'interface', 'vlan', 'ip', 'aaa',
    'ap', 'wlan', 'ssid', 'vap', 'ap-group', 'ap-name',
    'rf', 'arm', 'ids', 'wids', 'firewall', 'netservice',
    'acl', 'user-role', 'server-group', 'radius', 'tacacs',
    'ldap', 'xml-api', 'cp', 'captive-portal', 'vpn',
    'vrrp', 'hsrp', 'lacp', 'port-channel', 'loopback',
    'tunnel', 'gre', 'ipsec', 'ikev2', 'crypto', 'pki',
    'provision', 'reprovision', 'write', 'copy', 'erase',
    'ping', 'traceroute', 'aaa', 'database', 'local-userdb',
    'mgmt-server', 'airgroup', 'bt', 'avahi', 'dlna',
    'ha', 'synchronization', 'license',
    'wms', 'spectrum', 'rf-plan', 'mobility', 'anchor',
    'lc-cluster', 'mm', 'md', 'summary', 'detail',
    'ap-group', 'ap-name', 'ap-system-profile', 'regulatory',
    'rfprotect', 'wip', 'cppm-server', 'disable-airgroup',
    'managed-device', 'master-redundancy', 'database',
    'rap', ' rap-wizard', 'ids', 'wids',
  ],
  subcommands: [
    'profile', 'virtual-ap', 'aaa-profile', 'ssid-profile',
    'ap-group', 'ap-name', 'ap-system-profile', 'regulatory',
    'rf', 'radio', 'channel', 'power', 'tx-power', 'eirp',
    'band', 'mode', 'legacy', 'a-n', 'a-ac', 'g-n', 'ax',
    'beamforming', 'arm-rf-domain', 'ids-general-profile',
    'wmm', 'uapsd', 'band-steering', 'airmatch', 'client',
    'match', 'any', 'permit', 'deny', 'log', 'blacklist',
    'auth-failure', 'reauth-interval', 'dormancy',
    'association', 'disassociation', 'action', 'source',
    'destination', 'service', 'application', 'throttle',
    'qos', 'tos', 'dscp', '802.1p', 'wmm-access-category',
    'voice', 'video', 'best-effort', 'background',
    'lms', 'lms-ip', 'blms', 'blms-ip', 'backup-lms',
    'bandwidth-contract', 'vlan-pool', 'reauth',
    'airgroup-profile', 'cppm-server', 'ingress', 'egress', 'session',
    'user-vlan', 'vlan-id', 'user-idle-timeout', 'auth-server',
    'dot1x', 'mac', 'stateful-dot1x', 'captive-portal',
    'survival', 'backup', 'corporate', 'guest',
  ],
  keywords: [
    'enable', 'disable', 'default', 'exit', 'end', 'quit',
    'all', 'none', 'any', 'every', 'not', 'active', 'standby',
    'preferred', 'master', 'local', 'backup', 'lms', 'blms',
    'flat', 'tunnel', 'bridge', 'split-tunnel', 'decrypt',
    'forward', 'drop', 'src-nat', 'dst-nat', 'redirect',
    ' shaped', 'per-user', 'per-ap', 'per-ssid',
    'trust', 'dscp', '802.1p', 'wmm', 'tos',
    'required', 'optional', 'init-state',
  ],
  operators: ['|', '>', '<'],
  flags: ['--help', '-h', '| include', '| exclude', '| count', '| csv', '| sort', '| unique'],
  values: {
    ipAddress: /\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/,
    macAddress: /\b(?:[0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}\b/,
    vlanId: /\bvlan\s*(?:[1-9][0-9]{0,3}|409[0-5]|40[0-8][0-9]|[1-3][0-9]{3}|[1-9][0-9]{0,2})\b/,
    interfaceName: /\b(?:\d+\/\d+|port-channel\d+|loopback\d+|vlan\d+|tunnel\d+|gre\d+)\b/,
    number: /\b\d+\b/,
  },
  promptPattern: /^\(?(?:[A-Za-z][A-Za-z0-9-_\s]+\)\s*#\s?)/,
};
